import java.io.File
import java.security.SecureRandom
import java.util.Base64
import java.util.Properties
import java.util.concurrent.TimeUnit
import org.gradle.api.GradleException
import org.gradle.api.logging.Logger

/** What the tasks that run Minecraft servers share. */
object Servers {
    private val CACHES = setOf("cache", "libraries", "versions", "logs")

    fun requireEula(accepted: Boolean, what: String) {
        if (accepted) return
        throw GradleException(
            "$what runs a Minecraft server, which requires accepting the Minecraft EULA (https://aka.ms/MinecraftEULA). " +
                "Set -Pchestsplusplus.acceptMinecraftEula=true or ACCEPT_MINECRAFT_EULA=true."
        )
    }

    fun randomPassword(): String = Base64.getUrlEncoder().withoutPadding().encodeToString(ByteArray(18).also { SecureRandom().nextBytes(it) })

    /** Writes `server.properties` from [template] with [overrides], and accepts the EULA. */
    fun configure(runDir: File, template: File, overrides: Map<String, String>) {
        val properties = Properties()
        template.reader().use(properties::load)
        properties.putAll(overrides)
        runDir.mkdirs()
        File(runDir, "server.properties").writer().use { properties.store(it, "Generated by Gradle") }
        File(runDir, "eula.txt").writeText("eula=true\n")
    }

    /** Waits for the log to show `Done (`, failing if the server exits first or takes longer than [timeoutSeconds]. */
    fun waitForStart(process: Process, log: File, timeoutSeconds: Long, name: String) {
        val deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(timeoutSeconds)
        while (System.nanoTime() < deadline) {
            if (log.isFile && log.useLines { lines -> lines.any { it.contains("Done (") } }) return
            if (!process.isAlive) throw GradleException("The $name exited with code ${process.exitValue()} during startup. See $log")
            Thread.sleep(500)
        }
        kill(process.toHandle())
        throw GradleException("The $name did not start within ${timeoutSeconds}s. See $log")
    }

    fun kill(process: ProcessHandle) {
        process.descendants().forEach { it.destroyForcibly() }
        process.destroyForcibly()
    }

    /** Line numbers of the errors in [log] that mention one of [markers] (a plugin's name or package), or have it in their stack trace. */
    fun errorsFrom(log: File, markers: List<String>): List<Int> {
        val lines = log.readLines()
        fun mentions(line: String) = markers.any(line::contains)
        return lines.indices.filter { i ->
            (lines[i].contains("ERROR") || lines[i].contains("Exception")) &&
                (mentions(lines[i]) || lines.drop(i + 1).take(15).any { it.trimStart().startsWith("at ") && mentions(it) })
        }
    }

    /** The server's downloads and the logs: kept when a folder is cleared, and left out of snapshots. */
    fun isCacheOrLog(file: File) = file.name in CACHES || file.name.endsWith(".log")

    /** Empties [runDir] for a fresh start, keeping the server's downloads and the logs. */
    fun clear(runDir: File) {
        runDir.listFiles()?.filterNot(::isCacheOrLog)?.forEach { it.deleteRecursively() }
    }

    fun snapshot(runDir: File, snapshotDir: File) {
        snapshotDir.deleteRecursively()
        runDir.listFiles()?.filterNot(::isCacheOrLog)?.forEach { it.copyRecursively(File(snapshotDir, it.name), overwrite = true) }
    }
}

/**
 * A server a task runs in the foreground: [use] starts it, runs the body over RCON, then stops it, killing it if it won't stop.
 * The folder must already have its server.properties, with RCON on [rconPort] behind [password].
 */
class ForegroundServer(
    private val java: File,
    private val jvmArgs: List<String>,
    private val serverJar: File,
    private val runDir: File,
    private val rconPort: Int,
    private val password: String,
    private val name: String,
    private val logger: Logger,
) {
    fun <T> use(log: File, body: (Rcon) -> T): T {
        val command = listOf(java.absolutePath) + jvmArgs + listOf("-jar", serverJar.absolutePath, "--nogui")
        logger.lifecycle("Starting the $name in $runDir")
        val process = ProcessBuilder(command).directory(runDir).redirectErrorStream(true).redirectOutput(log).start()
        process.outputStream.close()
        try {
            Servers.waitForStart(process, log, 300, name)
            val result = Rcon("127.0.0.1", rconPort, password, timeoutMs = 120_000).use { rcon ->
                body(rcon).also { rcon.fire("stop") }
            }
            if (!process.waitFor(120, TimeUnit.SECONDS)) throw GradleException("The $name did not stop within 120s. See $log")
            return result
        } finally {
            if (process.isAlive) Servers.kill(process.toHandle())
        }
    }
}
